### ISSUE TITLE
little fix

### ISSUE THREAD

**Issue by weebzo** [Kokirix/KeyAuth#1]
https://github.com/Kokirix/KeyAuth/blob/3995a305017f32c18c85bea20c793fde55f24fbe/KeyAuth/Helper.cs#L93

instead of doing
`if (App.DownloadLink != null && !string.IsNullOrWhiteSpace(App.DownloadLink))`
just do 
`if (!string.IsNullOrWhiteSpace(App.DownloadLink))`
since the function already checks if the string is null

**Comment by Kokirix** [comment]
You're right, fixing that now.

**Comment by Kokirix** [comment]
Fixed!
