### ISSUE TITLE
Useless Parameter

### ISSUE THREAD

**Issue by weebzo** [Kokirix/KeyAuth#1]
https://github.com/Kokirix/KeyAuth/blob/b64e516edd5475f30fdf748c069920bc249acdf0/KeyAuth/Api.cs#L259

doesn't need that parameter, keyauth checks it automatically on server side.

**Comment by Kokirix** [comment]
Thanks for bringing this up, I actually removed it now.

**Comment by Kokirix** [comment]
Done
